# https://bazel.build/
# vim: set ft=python sts=2 sw=2 et:

cc_library(
  name = "common",
  srcs = ["common.cc"],
  hdrs = ["common.h"],
  deps = ["//base"],
  visibility = ["//visibility:public"],
)
